"use client";
import {createContext,useContext,useEffect,useState} from "react";

export type Lang="en"|"de"|"fr"|"es"|"zh";
const languages:[Lang,string,string][]=[["en","🇬🇧","English"],["de","🇩🇪","Deutsch"],["fr","🇫🇷","Français"],["es","🇪🇸","Español"],["zh","🇨🇳","中文"]];
const LanguageContext=createContext<{lang:Lang;setLang:(l:Lang)=>void}>({lang:"en",setLang:()=>{}});
export function LanguageProvider({children}:{children:React.ReactNode}){const [lang,setLang]=useState<Lang>("en");useEffect(()=>{document.documentElement.lang=lang==="zh"?"zh-CN":lang},[lang]);return <LanguageContext.Provider value={{lang,setLang}}>{children}</LanguageContext.Provider>}
export function useLanguage(){return useContext(LanguageContext)}
export function tx(lang:Lang,en:string,de:string,fr:string,es:string,zh:string){return {en,de,fr,es,zh}[lang]}
export function LanguageSwitcher({compact=false}:{compact?:boolean}){const {lang,setLang}=useLanguage();return <div className={`language-switcher${compact?" compact":""}`} aria-label="Language selection">{languages.map(([code,flag,label])=><button key={code} className={lang===code?"active":""} onClick={()=>setLang(code)} aria-pressed={lang===code} title={label}><span aria-hidden="true">{flag}</span><b>{compact?code.toUpperCase():label}</b></button>)}</div>}

const commonDe={"Grow in an existing international market":"In einem bestehenden internationalen Markt wachsen","Enter a new market":"Neuen Markt erschließen","Launch a new solution":"Neue Lösung einführen","Generate qualified leads":"Qualifizierte Leads generieren","Support sales":"Vertrieb unterstützen","Strengthen market position":"Marktposition stärken","Germany":"Deutschland","United States":"USA","Central Europe":"Mitteleuropa","North America":"Nordamerika","Global":"Global","Mechanical Engineering":"Maschinenbau","Technical Director":"Technischer Leiter","Design Engineer":"Konstruktionsingenieur","Purchasing Manager":"Einkaufsleiter","Managing Director":"Geschäftsführer","Maintenance Manager":"Instandhaltungsleiter","Distributor":"Vertriebspartner","New machine or system":"Neue Maschine / Anlage","New module":"Neues Modul","New feature or function":"Neues Feature / neue Funktion","New service":"Neuer Service","New product or component":"Neues Produkt / Bauteil","New partner or distributor":"Neuer Partner / Vertriebspartner","Product update or upgrade":"Produktupdate / Upgrade","Retrofit or modernization":"Retrofit / Modernisierung","Trade fair or product launch":"Messe / Produktlaunch","Reference project or customer success":"Referenzprojekt / Kundenerfolg"};
const commonFr={"Grow in an existing international market":"Croître sur un marché international existant","Enter a new market":"Entrer sur un nouveau marché","Launch a new solution":"Lancer une nouvelle solution","Generate qualified leads":"Générer des leads qualifiés","Support sales":"Soutenir les ventes","Strengthen market position":"Renforcer la position sur le marché","Germany":"Allemagne","United States":"États-Unis","Central Europe":"Europe centrale","North America":"Amérique du Nord","Global":"Global","Mechanical Engineering":"Construction mécanique","Technical Director":"Directeur technique","Design Engineer":"Ingénieur conception","Purchasing Manager":"Responsable achats","Managing Director":"Directeur général","Maintenance Manager":"Responsable maintenance","Distributor":"Distributeur","New machine or system":"Nouvelle machine / installation","New module":"Nouveau module","New feature or function":"Nouvelle fonctionnalité","New service":"Nouveau service","New product or component":"Nouveau produit / composant","New partner or distributor":"Nouveau partenaire / distributeur","Product update or upgrade":"Mise à jour / upgrade produit","Retrofit or modernization":"Retrofit / modernisation","Trade fair or product launch":"Salon / lancement produit","Reference project or customer success":"Projet de référence / succès client"};
const commonEs={"Grow in an existing international market":"Crecer en un mercado internacional existente","Enter a new market":"Entrar en un nuevo mercado","Launch a new solution":"Lanzar una nueva solución","Generate qualified leads":"Generar leads cualificados","Support sales":"Apoyar a ventas","Strengthen market position":"Reforzar la posición de mercado","Germany":"Alemania","United States":"Estados Unidos","Central Europe":"Europa Central","North America":"Norteamérica","Global":"Global","Mechanical Engineering":"Ingeniería mecánica","Technical Director":"Director técnico","Design Engineer":"Ingeniero de diseño","Purchasing Manager":"Responsable de compras","Managing Director":"Director general","Maintenance Manager":"Responsable de mantenimiento","Distributor":"Distribuidor","New machine or system":"Nueva máquina / sistema","New module":"Nuevo módulo","New feature or function":"Nueva función","New service":"Nuevo servicio","New product or component":"Nuevo producto / componente","New partner or distributor":"Nuevo socio / distribuidor","Product update or upgrade":"Actualización / upgrade","Retrofit or modernization":"Retrofit / modernización","Trade fair or product launch":"Feria / lanzamiento","Reference project or customer success":"Proyecto de referencia / caso de éxito"};
const commonZh={"Grow in an existing international market":"在现有国际市场增长","Enter a new market":"进入新市场","Launch a new solution":"推出新解决方案","Generate qualified leads":"获取高质量销售线索","Support sales":"支持销售","Strengthen market position":"强化市场地位","Germany":"德国","United States":"美国","Central Europe":"中欧","North America":"北美","Global":"全球","Mechanical Engineering":"机械工程","Technical Director":"技术总监","Design Engineer":"设计工程师","Purchasing Manager":"采购经理","Managing Director":"总经理","Maintenance Manager":"维护经理","Distributor":"经销商","New machine or system":"新机器 / 系统","New module":"新模块","New feature or function":"新功能","New service":"新服务","New product or component":"新产品 / 部件","New partner or distributor":"新合作伙伴 / 经销商","Product update or upgrade":"产品更新 / 升级","Retrofit or modernization":"改造 / 现代化","Trade fair or product launch":"展会 / 产品发布","Reference project or customer success":"标杆项目 / 客户成功"};
export const optionLabels:Record<Lang,Record<string,string>>={en:{},de:commonDe,fr:commonFr,es:commonEs,zh:commonZh};
export function ol(lang:Lang,value:string){return optionLabels[lang][value]||value}
