"use client";
import {createContext,useContext,useEffect,useState} from "react";

export type Lang="en"|"de"|"fr"|"es"|"zh";
const languages:[Lang,string,string][]=[
 ["en","🇬🇧","English"],["de","🇩🇪","Deutsch"],["fr","🇫🇷","Français"],["es","🇪🇸","Español"],["zh","🇨🇳","中文"]
];
const LanguageContext=createContext<{lang:Lang;setLang:(l:Lang)=>void}>({lang:"en",setLang:()=>{}});
export function LanguageProvider({children}:{children:React.ReactNode}){const [lang,setLang]=useState<Lang>("en");useEffect(()=>{document.documentElement.lang=lang==="zh"?"zh-CN":lang},[lang]);return <LanguageContext.Provider value={{lang,setLang}}>{children}</LanguageContext.Provider>}
export function useLanguage(){return useContext(LanguageContext)}
export function tx(lang:Lang,en:string,de:string,fr:string,es:string,zh:string){return {en,de,fr,es,zh}[lang]}
export function LanguageSwitcher({compact=false}:{compact?:boolean}){const {lang,setLang}=useLanguage();return <div className={`language-switcher${compact?" compact":""}`} aria-label="Language selection">{languages.map(([code,flag,label])=><button key={code} className={lang===code?"active":""} onClick={()=>setLang(code)} aria-pressed={lang===code} title={label}><span aria-hidden="true">{flag}</span><b>{compact?code.toUpperCase():label}</b></button>)}</div>}

export const optionLabels:Record<Lang,Record<string,string>>={
 en:{},
 de:{"Grow in an existing international market":"In einem bestehenden internationalen Markt wachsen","Enter a new market":"Neuen Markt erschließen","Launch a new solution":"Neue Lösung einführen","Generate qualified leads":"Qualifizierte Leads generieren","Support sales":"Vertrieb unterstützen","Strengthen market position":"Marktposition stärken","Modular production system":"Modulares Produktionssystem","Industrial automation solution":"Industrielle Automatisierungslösung","Production technology platform":"Produktionstechnologie-Plattform","Technical service solution":"Technische Servicelösung","Industrial component system":"Industrielles Komponentensystem","Germany":"Deutschland","United States":"USA","France":"Frankreich","United Kingdom":"Vereinigtes Königreich","Central Europe":"Mitteleuropa","North America":"Nordamerika","Global":"Global","Industrial Manufacturing":"Industrielle Fertigung","Mechanical Engineering":"Maschinenbau","Packaging":"Verpackung","Material Handling":"Materialfluss","Automotive":"Automotive","Agricultural Machinery":"Landtechnik","Technical Director":"Technischer Leiter","Design Engineer":"Konstruktionsingenieur","Purchasing Manager":"Einkaufsleiter","Managing Director":"Geschäftsführer","Maintenance Manager":"Instandhaltungsleiter","Distributor":"Vertriebspartner"},
 fr:{"Grow in an existing international market":"Croître sur un marché international existant","Enter a new market":"Entrer sur un nouveau marché","Launch a new solution":"Lancer une nouvelle solution","Generate qualified leads":"Générer des leads qualifiés","Support sales":"Soutenir les ventes","Strengthen market position":"Renforcer la position sur le marché","Modular production system":"Système de production modulaire","Industrial automation solution":"Solution d’automatisation industrielle","Production technology platform":"Plateforme de technologie de production","Technical service solution":"Solution de service technique","Industrial component system":"Système de composants industriels","Germany":"Allemagne","United States":"États-Unis","France":"France","United Kingdom":"Royaume-Uni","Central Europe":"Europe centrale","North America":"Amérique du Nord","Global":"Global","Industrial Manufacturing":"Production industrielle","Mechanical Engineering":"Construction mécanique","Packaging":"Emballage","Material Handling":"Manutention","Automotive":"Automobile","Agricultural Machinery":"Machines agricoles","Technical Director":"Directeur technique","Design Engineer":"Ingénieur conception","Purchasing Manager":"Responsable achats","Managing Director":"Directeur général","Maintenance Manager":"Responsable maintenance","Distributor":"Distributeur"},
 es:{"Grow in an existing international market":"Crecer en un mercado internacional existente","Enter a new market":"Entrar en un nuevo mercado","Launch a new solution":"Lanzar una nueva solución","Generate qualified leads":"Generar leads cualificados","Support sales":"Apoyar a ventas","Strengthen market position":"Reforzar la posición de mercado","Modular production system":"Sistema de producción modular","Industrial automation solution":"Solución de automatización industrial","Production technology platform":"Plataforma de tecnología de producción","Technical service solution":"Solución de servicio técnico","Industrial component system":"Sistema de componentes industriales","Germany":"Alemania","United States":"Estados Unidos","France":"Francia","United Kingdom":"Reino Unido","Central Europe":"Europa Central","North America":"Norteamérica","Global":"Global","Industrial Manufacturing":"Fabricación industrial","Mechanical Engineering":"Ingeniería mecánica","Packaging":"Embalaje","Material Handling":"Manipulación de materiales","Automotive":"Automoción","Agricultural Machinery":"Maquinaria agrícola","Technical Director":"Director técnico","Design Engineer":"Ingeniero de diseño","Purchasing Manager":"Responsable de compras","Managing Director":"Director general","Maintenance Manager":"Responsable de mantenimiento","Distributor":"Distribuidor"},
 zh:{"Grow in an existing international market":"在现有国际市场增长","Enter a new market":"进入新市场","Launch a new solution":"推出新解决方案","Generate qualified leads":"获取高质量销售线索","Support sales":"支持销售","Strengthen market position":"强化市场地位","Modular production system":"模块化生产系统","Industrial automation solution":"工业自动化解决方案","Production technology platform":"生产技术平台","Technical service solution":"技术服务解决方案","Industrial component system":"工业组件系统","Germany":"德国","United States":"美国","France":"法国","United Kingdom":"英国","Central Europe":"中欧","North America":"北美","Global":"全球","Industrial Manufacturing":"工业制造","Mechanical Engineering":"机械工程","Packaging":"包装","Material Handling":"物料搬运","Automotive":"汽车","Agricultural Machinery":"农业机械","Technical Director":"技术总监","Design Engineer":"设计工程师","Purchasing Manager":"采购经理","Managing Director":"总经理","Maintenance Manager":"维护经理","Distributor":"经销商"}
};
export function ol(lang:Lang,value:string){return optionLabels[lang][value]||value}
