"use client";
import {useEffect,useRef} from "react";import {PersonalSection} from "./personal-section";import {tx,useLanguage} from "./i18n";

export function LocalizedPersonalSection(){
  const {lang}=useLanguage(),ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const root=ref.current;if(!root)return;const label=root.querySelector<HTMLElement>(".personal-copy .label"),title=root.querySelector<HTMLElement>("#personal-title"),lede=root.querySelector<HTMLElement>(".personal-lede"),paras=root.querySelectorAll<HTMLElement>(".personal-copy>p"),fig=root.querySelector<HTMLElement>("figcaption"),img=root.querySelector<HTMLImageElement>("img"),steps=root.querySelectorAll<HTMLElement>(".personal-process span");if(label)label.textContent=tx(lang,"MY WAY OF WORKING","MEINE ARBEITSWEISE","MA FAÇON DE TRAVAILLER","MI FORMA DE TRABAJAR","我的工作方式");if(title)title.innerHTML=tx(lang,"I START<br/>BY LISTENING.","ICH BEGINNE<br/>MIT ZUHÖREN.","JE COMMENCE<br/>PAR ÉCOUTER.","EMPIEZO<br/>ESCUCHANDO.","我从<br/>倾听开始。");if(fig)fig.textContent=tx(lang,"A real whiteboard moment · thinking in progress","Ein echter Whiteboard-Moment · Denken im Prozess","Un vrai moment au tableau · réflexion en cours","Un momento real de pizarra · pensamiento en proceso","真实的白板时刻 · 思考正在发生");if(img)img.alt=tx(lang,"Ricardo Lavoie working at a whiteboard","Ricardo Lavoie bei der Arbeit am Whiteboard","Ricardo Lavoie travaillant au tableau","Ricardo Lavoie trabajando en una pizarra","Ricardo Lavoie在白板前工作");if(lede)lede.textContent=tx(lang,"Before changing anything, I want to understand what already works — and what people close to customers, products and markets already know.","Bevor ich etwas verändere, möchte ich verstehen, was bereits funktioniert – und welches Wissen bei den Menschen vorhanden ist, die nah an Kunden, Produkten und Märkten arbeiten.","Avant de changer quoi que ce soit, je veux comprendre ce qui fonctionne déjà — et ce que savent les personnes proches des clients, des produits et des marchés.","Antes de cambiar nada, quiero entender qué funciona ya y qué saben las personas cercanas a clientes, productos y mercados.","在改变任何事情之前，我先理解哪些已经有效，以及最接近客户、产品和市场的人掌握了什么知识。");if(paras[2])paras[2].textContent=tx(lang,"My role as a marketing leader is to connect these perspectives, create direction and develop the next step together with the people involved.","Meine Aufgabe als Marketingleiter ist es, diese Perspektiven zu verbinden, Richtung zu schaffen und den nächsten Schritt gemeinsam mit den Beteiligten zu entwickeln.","Mon rôle de leader marketing est de relier ces perspectives, de donner une direction et de développer la prochaine étape avec les personnes concernées.","Mi función como líder de marketing es conectar estas perspectivas, crear dirección y desarrollar el siguiente paso junto a las personas implicadas.","作为营销领导者，我的职责是连接这些视角、形成方向，并与相关人员共同推进下一步。");const stepCopy=tx(lang,"LISTEN|UNDERSTAND|CONNECT|DEVELOP","ZUHÖREN|VERSTEHEN|VERBINDEN|ENTWICKELN","ÉCOUTER|COMPRENDRE|RELIER|DÉVELOPPER","ESCUCHAR|ENTENDER|CONECTAR|DESARROLLAR","倾听|理解|连接|发展").split("|");steps.forEach((s,i)=>s.textContent=stepCopy[i]||s.textContent)},[lang]);

  const strengths=[
    [tx(lang,"LEADERSHIP","FÜHRUNG","LEADERSHIP","LIDERAZGO","领导力"),tx(lang,"Develop teams · create direction","Teams entwickeln · Orientierung geben","Développer les équipes · donner une direction","Desarrollar equipos · crear dirección","发展团队 · 明确方向")],
    [tx(lang,"INTERNATIONAL","INTERNATIONAL","INTERNATIONAL","INTERNACIONAL","国际化"),tx(lang,"North America · international B2B markets","Nordamerika · internationale B2B-Märkte","Amérique du Nord · marchés B2B internationaux","Norteamérica · mercados B2B internacionales","北美 · 国际B2B市场")],
    [tx(lang,"BRAND & GROWTH","MARKE & WACHSTUM","MARQUE & CROISSANCE","MARCA & CRECIMIENTO","品牌与增长"),tx(lang,"Brand leadership · communication · sales","Markenführung · Kommunikation · Vertrieb","Marque · communication · ventes","Marca · comunicación · ventas","品牌管理 · 传播 · 销售")],
    [tx(lang,"TRANSFORMATION","TRANSFORMATION","TRANSFORMATION","TRANSFORMACIÓN","转型"),tx(lang,"Processes · digitalization · AI enablement","Prozesse · Digitalisierung · KI-Unterstützung","Processus · digitalisation · IA","Procesos · digitalización · IA","流程 · 数字化 · AI赋能")]
  ];

  return <div ref={ref} className="personal-localized"><PersonalSection/><section className="executive-profile"><p className="poster-kicker">{tx(lang,"MARKETING LEADERSHIP","MARKETING LEADERSHIP","LEADERSHIP MARKETING","LIDERAZGO DE MARKETING","营销领导力")}</p><h2>{tx(lang,"LEADING PEOPLE.\nCONNECTING MARKETS.\nDEVELOPING MARKETING.","MENSCHEN FÜHREN.\nMÄRKTE VERBINDEN.\nMARKETING ENTWICKELN.","DIRIGER LES ÉQUIPES.\nRELIER LES MARCHÉS.\nFAIRE ÉVOLUER LE MARKETING.","LIDERAR PERSONAS.\nCONECTAR MERCADOS.\nDESARROLLAR MARKETING.","领导团队。\n连接市场。\n发展营销。")}</h2><p className="executive-intro">{tx(lang,"My experience combines team leadership, international B2B marketing, brand development and transformation — from creative leadership and the North American market to marketing management and AI-enabled processes.","Meine Erfahrung verbindet Teamführung, internationales B2B-Marketing, Markenentwicklung und Transformation – von Creative Leadership und dem nordamerikanischen Markt bis zu Marketingleitung und KI-gestützten Prozessen.","Mon expérience associe management d’équipe, marketing B2B international, développement de marque et transformation — de la direction créative et du marché nord-américain au management marketing et aux processus soutenus par l’IA.","Mi experiencia combina liderazgo de equipos, marketing B2B internacional, desarrollo de marca y transformación — desde la dirección creativa y el mercado norteamericano hasta la gestión de marketing y los procesos apoyados por IA.","我的经验涵盖团队领导、国际B2B营销、品牌发展与转型——从创意领导和北美市场，到营销管理与AI支持的流程。")}</p><div className="executive-strengths">{strengths.map(([title,copy])=><article key={title}><b>{title}</b><span>{copy}</span></article>)}</div><div className="recognition"><p className="poster-kicker">{tx(lang,"RECOGNITION","AUSZEICHNUNGEN","DISTINCTIONS","RECONOCIMIENTOS","荣誉")}</p><h3>RED DOT AWARD · BUNDESKANZLERPREIS · INTERACTIVE MEDIA AWARD · INTERNATIONAL CREATIVITY AWARD</h3><p>{tx(lang,"Recognition for work in communication, digital design and creative direction.","Auszeichnungen für Arbeiten in Kommunikation, digitalem Design und Creative Direction.","Distinctions pour des travaux en communication, design numérique et direction créative.","Reconocimientos por trabajos en comunicación, diseño digital y dirección creativa.","在传播、数字设计与创意指导领域获得的专业认可。")}</p><p className="publication">{tx(lang,"Also published: Master’s thesis in Interaction Design.","Außerdem veröffentlicht: Masterarbeit im Bereich Interaction Design.","Également publié : mémoire de master en Interaction Design.","También publicado: tesis de máster en Interaction Design.","另有出版成果：交互设计硕士论文。")}</p></div></section></div>;
}
