"use client";
import {useState} from "react";
import {ol,tx,useLanguage} from "./i18n";
import {LanguageDropdown} from "./language-dropdown";
import {ApplicationEdition} from "./application-edition";
import {LocalizedPersonalSection} from "./localized-personal-section";
import {buildApproach} from "@/lib/approach";
import type {Context} from "@/types";

const markets=["Germany","Central Europe","United States","North America","Global"];
const roles=["Technical Director","Design Engineer","Purchasing Manager","Managing Director","Maintenance Manager","Distributor"];
const goals=["Grow in an existing international market","Enter a new market","Launch a new solution","Generate qualified leads","Support sales","Strengthen market position"];
const solutions=["Industrial automation solution","Modular production system","Production technology platform","Technical service solution","Industrial component system"];
const channels=["LinkedIn","Email","Newsletter","Website","Phone","Trade Fair"];
const base:Context={objective:"Strengthen market position",solution:"Industrial automation solution",market:"Germany",industry:"Mechanical Engineering",role:"Technical Director"};

function ComplexityScribble(){return <svg viewBox="0 0 420 360" role="img" aria-label="Dense hand-drawn complexity scribble"><g fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"><path d="M74 167 C34 92 105 35 185 78 C268 121 246 223 169 232 C91 240 45 175 82 118 C126 51 245 50 304 116 C356 175 326 270 246 278 C160 287 86 229 100 155 C116 69 235 36 313 98 C385 155 347 278 253 303 C161 327 70 266 63 184 C57 108 122 53 205 54 C301 55 359 125 344 203 C330 279 244 323 166 291 C90 260 49 183 81 115"/><path d="M127 132 C155 78 236 82 272 130 C308 178 278 246 221 251 C157 257 111 205 126 151 C141 94 215 72 263 108 C313 145 299 218 246 242 C192 267 134 226 128 176 C122 127 166 94 216 101 C264 108 287 150 272 190 C255 235 194 242 160 211 C124 178 142 126 181 112 C225 96 263 126 261 169 C259 208 219 228 185 211 C148 193 150 147 181 127 C215 105 252 128 251 162 C250 195 219 210 192 196 C165 182 166 150 190 137 C215 124 240 142 236 166 C233 189 207 198 190 183 C172 168 184 143 204 141 C223 139 233 157 224 171"/><path d="M95 255 C45 229 31 165 63 121 M295 76 C352 90 382 139 369 195 M326 269 C283 326 203 342 139 309 M111 72 C155 25 228 20 286 55"/><path d="M150 89 C121 137 118 195 150 241 C187 293 270 286 305 229 C340 173 315 99 253 78 C194 59 136 93 117 145 C98 198 129 257 182 274 C239 292 296 255 309 202 C322 148 287 94 232 83 C180 73 131 106 121 156 C110 205 143 250 192 259 C239 267 282 236 288 190 C294 149 266 111 224 106 C183 101 149 128 146 168 C143 205 169 234 206 236 C240 238 269 213 270 178 C271 146 249 121 217 121 C186 121 165 145 166 174 C167 201 188 220 215 217 C240 215 256 194 251 170 C247 147 227 135 207 141 C188 147 181 167 189 184 C198 202 219 205 232 192"/></g></svg>}

function DirectionScribble(){return <svg viewBox="0 0 760 120" role="img" aria-label="Scribble resolving into a clear direction"><path d="M8 65 C35 15 80 18 82 62 C85 108 25 103 31 54 C38 6 122 10 130 60 C139 110 61 111 67 54 C73 5 168 11 176 60 C185 111 108 111 114 52 C120 8 213 7 220 59 C226 105 161 107 163 58 C166 18 250 15 257 61 C262 100 213 103 210 67 C251 82 291 82 328 70 C383 51 439 60 495 68 C559 76 625 70 718 42" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M696 31 L727 41 L705 59" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg>}

function PositioningSignals(){const {lang}=useLanguage();const data=[
 ["◎",tx(lang,"INTERNATIONAL EXPERIENCE","INTERNATIONALE ERFAHRUNG","EXPÉRIENCE INTERNATIONALE","EXPERIENCIA INTERNACIONAL","国际经验"),tx(lang,"Understand markets. Think globally.","Märkte verstehen. Global denken.","Comprendre les marchés. Penser global.","Entender mercados. Pensar globalmente.","理解市场。全球思考。")],
 ["◯◯◯",tx(lang,"PEOPLE & TEAMS","MENSCHEN & TEAMS","PERSONNES & ÉQUIPES","PERSONAS & EQUIPOS","人才与团队"),tx(lang,"Listen. Understand. Develop together.","Zuhören. Verstehen. Gemeinsam entwickeln.","Écouter. Comprendre. Développer ensemble.","Escuchar. Entender. Desarrollar juntos.","倾听。理解。共同发展。")],
 ["↗",tx(lang,"GROWTH & IMPACT","WACHSTUM & WIRKUNG","CROISSANCE & IMPACT","CRECIMIENTO & IMPACTO","增长与影响"),tx(lang,"Strategy that works. Measurable. Sustainable.","Strategie, die wirkt. Messbar. Nachhaltig.","Une stratégie qui agit. Mesurable. Durable.","Estrategia que funciona. Medible. Sostenible.","有效战略。可衡量。可持续。")]
 ];return <div className="hero-signals">{data.map(([icon,title,copy])=><div className="hero-signal" key={title}><span className="signal-icon" aria-hidden="true">{icon}</span><b>{title}</b><p>{copy}</p></div>)}</div>}

function activationCopy(lang:ReturnType<typeof useLanguage>["lang"],channel:string,role:string){const ch=ol(lang,channel),r=ol(lang,role);return tx(lang,
 `${ch}: adapt the core message into a concrete touchpoint for the ${r}. Keep one strategic message, but change format, depth and call-to-action for the channel.`,
 `${ch}: Die Kernbotschaft wird in einen konkreten Kontaktpunkt für ${r} übersetzt. Die Strategie bleibt gleich – Format, Detailtiefe und Call-to-Action werden an den Kanal angepasst.`,
 `${ch} : traduire le message central en un point de contact concret pour ${r}. La stratégie reste cohérente, tandis que le format, le niveau de détail et l’appel à l’action s’adaptent au canal.`,
 `${ch}: convertir el mensaje central en un punto de contacto concreto para ${r}. La estrategia se mantiene; formato, profundidad y llamada a la acción se adaptan al canal.`,
 `${ch}：把核心信息转化为面向${r}的具体触点。战略保持一致，但形式、信息深度和行动号召根据渠道调整。`)}

export default function PosterSite(){const {lang}=useLanguage();const [draft,setDraft]=useState(base),[ctx,setCtx]=useState(base),[channel,setChannel]=useState("LinkedIn"),[built,setBuilt]=useState(false);const a=buildApproach(ctx,lang);const build=()=>{setCtx(draft);setBuilt(true);setTimeout(()=>document.querySelector("#example")?.scrollIntoView({behavior:"smooth"}),40)};return <>
<header className="poster-hero" id="top"><div className="hero-application"><ApplicationEdition/></div><nav><b>B2B MARKETING INTELLIGENCE LAB</b><LanguageDropdown/></nav><div className="hero-stage"><div className="hero-title-row"><h1>{tx(lang,"FROM\nCOMPLEXITY\nTO CLARITY.","VON\nKOMPLEXITÄT\nZU KLARHEIT.","DE LA\nCOMPLEXITÉ\nÀ LA CLARTÉ.","DE LA\nCOMPLEJIDAD\nA LA CLARIDAD.","从复杂\n到清晰。")}</h1><div className="hero-complexity-scribble"><ComplexityScribble/></div></div><div className="hero-lower-row"><div className="hero-copy"><span className="hero-rule"/><p className="poster-intro">{tx(lang,"Product knowledge becomes relevant communication for markets, customers and sales.","Produktwissen wird zu relevanter Kommunikation für Märkte, Kunden und Vertrieb.","Le savoir produit devient une communication pertinente pour les marchés, les clients et les ventes.","El conocimiento de producto se convierte en comunicación relevante para mercados, clientes y ventas.","产品知识转化为面向市场、客户和销售的相关沟通。")}</p><a className="primary poster-cta" href="#lab">{tx(lang,"EXPLORE ONE EXAMPLE →","EIN BEISPIEL ANSEHEN →","VOIR UN EXEMPLE →","VER UN EJEMPLO →","查看示例 →")}</a><div className="hero-direction-scribble"><DirectionScribble/></div><PositioningSignals/></div><figure className="hero-portrait"><img src="/ricardo-portrait.jpg" alt="Ricardo Lavoie"/></figure></div></div></header>

<section className="poster-problem"><p className="poster-kicker">01 / {tx(lang,"THE CHALLENGE","DIE HERAUSFORDERUNG","LE DÉFI","EL RETO","挑战")}</p><h2>{tx(lang,"ONE BRAND.\nMANY MARKETS.\nRELEVANT MESSAGES.","EINE MARKE.\nVIELE MÄRKTE.\nRELEVANTE BOTSCHAFTEN.","UNE MARQUE.\nPLUSIEURS MARCHÉS.\nDES MESSAGES PERTINENTS.","UNA MARCA.\nMUCHOS MERCADOS.\nMENSAJES RELEVANTES.","一个品牌。\n多个市场。\n相关信息。")}</h2><p>{tx(lang,"The challenge is not producing more content. It is connecting product knowledge with the right market, customer need and sales situation.","Die Herausforderung ist nicht mehr Content. Entscheidend ist, Produktwissen mit dem richtigen Markt, Kundenbedarf und der Vertriebssituation zu verbinden.","Le défi n’est pas de produire plus de contenu, mais de relier le savoir produit au bon marché, au besoin client et à la situation commerciale.","El reto no es producir más contenido, sino conectar el conocimiento del producto con el mercado, la necesidad del cliente y la situación comercial adecuados.","挑战不是生产更多内容，而是把产品知识与正确的市场、客户需求和销售场景连接起来。")}</p></section>

<section id="lab" className="poster-lab"><p className="poster-kicker">02 / {tx(lang,"EXPLORE A MARKET OPPORTUNITY","MARKTCHANCE ERKUNDEN","EXPLORER UNE OPPORTUNITÉ","EXPLORAR UNA OPORTUNIDAD","探索市场机会")}</p><h2>{tx(lang,"CHOOSE A CONTEXT.\nSEE THE THINKING.","KONTEXT WÄHLEN.\nDENKWEISE ERLEBEN.","CHOISIR UN CONTEXTE.\nVOIR LA LOGIQUE.","ELIGE UN CONTEXTO.\nVE LA LÓGICA.","选择情境。\n查看思路。")}</h2><div className="poster-selectors five"><label><span>{tx(lang,"SOLUTION","LÖSUNG","SOLUTION","SOLUCIÓN","解决方案")}</span><select value={draft.solution} onChange={e=>setDraft({...draft,solution:e.target.value})}>{solutions.map(x=><option key={x} value={x}>{ol(lang,x)}</option>)}</select></label><label><span>{tx(lang,"MARKET","MARKT","MARCHÉ","MERCADO","市场")}</span><select value={draft.market} onChange={e=>setDraft({...draft,market:e.target.value})}>{markets.map(x=><option key={x} value={x}>{ol(lang,x)}</option>)}</select></label><label><span>{tx(lang,"BUYING ROLE","ENTSCHEIDER","RÔLE ACHETEUR","ROL DE COMPRA","购买角色")}</span><select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}>{roles.map(x=><option key={x} value={x}>{ol(lang,x)}</option>)}</select></label><label><span>{tx(lang,"OBJECTIVE","ZIEL","OBJECTIF","OBJETIVO","目标")}</span><select value={draft.objective} onChange={e=>setDraft({...draft,objective:e.target.value})}>{goals.map(x=><option key={x} value={x}>{ol(lang,x)}</option>)}</select></label><label><span>{tx(lang,"CHANNEL","KANAL","CANAL","CANAL","渠道")}</span><select value={channel} onChange={e=>setChannel(e.target.value)}>{channels.map(x=><option key={x} value={x}>{ol(lang,x)}</option>)}</select></label></div><button className="primary" onClick={build}>{tx(lang,"BUILD MARKET APPROACH →","MARKTANSATZ ERSTELLEN →","CRÉER L’APPROCHE →","CREAR ENFOQUE →","生成市场方案 →")}</button>{built&&<div id="example" className="poster-results four"><article><b>01 / {tx(lang,"MARKET HYPOTHESIS","MARKTHYPOTHESE","HYPOTHÈSE MARCHÉ","HIPÓTESIS DE MERCADO","市场假设")}</b><p>{a.hypothesis}</p></article><article><b>02 / {tx(lang,"VALUE PROPOSITION","NUTZENVERSPRECHEN","PROPOSITION DE VALEUR","PROPUESTA DE VALOR","价值主张")}</b><p>{a.value}</p></article><article><b>03 / {tx(lang,"CORE MESSAGE","KERNBOTSCHAFT","MESSAGE CENTRAL","MENSAJE CENTRAL","核心信息")}</b><h3>{a.core}</h3></article><article><b>04 / {tx(lang,"CHANNEL ACTIVATION","KANAL-AKTIVIERUNG","ACTIVATION DU CANAL","ACTIVACIÓN DEL CANAL","渠道激活")}</b><p>{activationCopy(lang,channel,ctx.role)}</p></article><small>{tx(lang,"AI SUPPORTS · PEOPLE VALIDATE · SALES LEARNS","KI UNTERSTÜTZT · MENSCHEN VALIDIEREN · VERTRIEB LERNT","L’IA SOUTIENT · L’HUMAIN VALIDE · LES VENTES APPRENNENT","LA IA APOYA · LAS PERSONAS VALIDAN · VENTAS APRENDE","AI支持 · 人工验证 · 销售反馈学习")}</small></div>}</section>

<LocalizedPersonalSection/>
<section className="poster-ai"><p className="poster-kicker">04 / {tx(lang,"MY PRINCIPLE","MEIN PRINZIP","MON PRINCIPE","MI PRINCIPIO","我的原则")}</p><h2>{tx(lang,"AI IS NOT\nTHE STRATEGY.","KI IST NICHT\nDIE STRATEGIE.","L’IA N’EST PAS\nLA STRATÉGIE.","LA IA NO ES\nLA ESTRATEGIA.","AI不是\n战略。")}</h2><h3>{tx(lang,"AI SCALES THE SYSTEM.\nPEOPLE OWN THE DECISIONS.","KI SKALIERT DAS SYSTEM.\nMENSCHEN TREFFEN DIE ENTSCHEIDUNGEN.","L’IA FAIT ÉVOLUER LE SYSTÈME.\nLES HUMAINS DÉCIDENT.","LA IA ESCALA EL SISTEMA.\nLAS PERSONAS DECIDEN.","AI帮助规模化。\n人做最终决策。")}</h3></section>
<section className="poster-close"><p className="poster-kicker">05 / {tx(lang,"THE POINT","DER PUNKT","L’IDÉE","LA IDEA","核心")}</p><h2>{tx(lang,"GOOD MARKETING\nIS BUILT WITH PEOPLE,\nNOT FOR THEM.","GUTES MARKETING\nENTSTEHT MIT MENSCHEN,\nNICHT FÜR SIE.","LE BON MARKETING\nSE CONSTRUIT AVEC LES GENS,\nPAS POUR EUX.","EL BUEN MARKETING\nSE CONSTRUYE CON PERSONAS,\nNO PARA ELLAS.","好的营销\n与人共同创造，\n而不是替人创造。")}</h2><p>{tx(lang,"This is not a proposal for the client company. It is a purpose-built glimpse into how I think about international B2B marketing leadership.","Dies ist kein Konzeptvorschlag für das Mandantenunternehmen, sondern ein gezielter Einblick in meine Denkweise zu internationaler B2B-Marketingführung.","Ce n’est pas une proposition pour l’entreprise cliente, mais un aperçu ciblé de ma façon de penser le leadership marketing B2B international.","No es una propuesta para la empresa cliente, sino una mirada concreta a cómo pienso el liderazgo de marketing B2B internacional.","这不是客户公司的方案，而是对我如何思考国际B2B营销领导力的简洁展示。")}</p></section>
<ApplicationEdition footer/><footer className="poster-footer"><div><h2>Ricardo Lavoie, M.A.</h2><p>MARKETING STRATEGY · INTERNATIONAL B2B · BRAND · AI & AUTOMATION</p></div><LanguageDropdown/><a href="#top">{tx(lang,"Back to top ↑","Nach oben ↑","Retour en haut ↑","Volver arriba ↑","返回顶部 ↑")}</a></footer></>}
